// Code generated by goctl. DO NOT EDIT.
// Source: analyst.proto

package server

import (
	"context"

	"rsapi/stock/rpc/analyst/analyst"
	"rsapi/stock/rpc/analyst/internal/logic"
	"rsapi/stock/rpc/analyst/internal/svc"
)

type AnalystServer struct {
	svcCtx *svc.ServiceContext
	analyst.UnimplementedAnalystServer
}

func NewAnalystServer(svcCtx *svc.ServiceContext) *AnalystServer {
	return &AnalystServer{
		svcCtx: svcCtx,
	}
}

func (s *AnalystServer) Ping(ctx context.Context, in *analyst.Request) (*analyst.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
