// Code generated by goctl. DO NOT EDIT.
// Source: converter.proto

package server

import (
	"context"

	"rsapi/devtoys/rpc/converter/converter"
	"rsapi/devtoys/rpc/converter/internal/logic"
	"rsapi/devtoys/rpc/converter/internal/svc"
)

type ConverterServer struct {
	svcCtx *svc.ServiceContext
	converter.UnimplementedConverterServer
}

func NewConverterServer(svcCtx *svc.ServiceContext) *ConverterServer {
	return &ConverterServer{
		svcCtx: svcCtx,
	}
}

func (s *ConverterServer) Ping(ctx context.Context, in *converter.Request) (*converter.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
