// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	authRoleFieldNames          = builder.RawFieldNames(&AuthRole{})
	authRoleRows                = strings.Join(authRoleFieldNames, ",")
	authRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(authRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	authRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(authRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAuthRoleIdPrefix   = "cache:authRole:id:"
	cacheAuthRoleNamePrefix = "cache:authRole:name:"
)

type (
	authRoleModel interface {
		Insert(ctx context.Context, data *AuthRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AuthRole, error)
		FindOneByName(ctx context.Context, name string) (*AuthRole, error)
		Update(ctx context.Context, data *AuthRole) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuthRoleModel struct {
		sqlc.CachedConn
		table string
	}

	AuthRole struct {
		Id       int64     `db:"id"`        // role table id
		Name     string    `db:"name"`      // role name
		CreateAt time.Time `db:"create_at"` // create time
		UpdateAt time.Time `db:"update_at"` // update time
	}
)

func newAuthRoleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAuthRoleModel {
	return &defaultAuthRoleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`auth_role`",
	}
}

func (m *defaultAuthRoleModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	authRoleIdKey := fmt.Sprintf("%s%v", cacheAuthRoleIdPrefix, id)
	authRoleNameKey := fmt.Sprintf("%s%v", cacheAuthRoleNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, authRoleIdKey, authRoleNameKey)
	return err
}

func (m *defaultAuthRoleModel) FindOne(ctx context.Context, id int64) (*AuthRole, error) {
	authRoleIdKey := fmt.Sprintf("%s%v", cacheAuthRoleIdPrefix, id)
	var resp AuthRole
	err := m.QueryRowCtx(ctx, &resp, authRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthRoleModel) FindOneByName(ctx context.Context, name string) (*AuthRole, error) {
	authRoleNameKey := fmt.Sprintf("%s%v", cacheAuthRoleNamePrefix, name)
	var resp AuthRole
	err := m.QueryRowIndexCtx(ctx, &resp, authRoleNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", authRoleRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuthRoleModel) Insert(ctx context.Context, data *AuthRole) (sql.Result, error) {
	authRoleIdKey := fmt.Sprintf("%s%v", cacheAuthRoleIdPrefix, data.Id)
	authRoleNameKey := fmt.Sprintf("%s%v", cacheAuthRoleNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?)", m.table, authRoleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name)
	}, authRoleIdKey, authRoleNameKey)
	return ret, err
}

func (m *defaultAuthRoleModel) Update(ctx context.Context, newData *AuthRole) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	authRoleIdKey := fmt.Sprintf("%s%v", cacheAuthRoleIdPrefix, data.Id)
	authRoleNameKey := fmt.Sprintf("%s%v", cacheAuthRoleNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, authRoleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.Id)
	}, authRoleIdKey, authRoleNameKey)
	return err
}

func (m *defaultAuthRoleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAuthRoleIdPrefix, primary)
}

func (m *defaultAuthRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", authRoleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAuthRoleModel) tableName() string {
	return m.table
}
