// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mallOrderFieldNames          = builder.RawFieldNames(&MallOrder{})
	mallOrderRows                = strings.Join(mallOrderFieldNames, ",")
	mallOrderRowsExpectAutoSet   = strings.Join(stringx.Remove(mallOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mallOrderRowsWithPlaceHolder = strings.Join(stringx.Remove(mallOrderFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMallOrderIdPrefix = "cache:mallOrder:id:"
)

type (
	mallOrderModel interface {
		Insert(ctx context.Context, data *MallOrder) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MallOrder, error)
		Update(ctx context.Context, data *MallOrder) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMallOrderModel struct {
		sqlc.CachedConn
		table string
	}

	MallOrder struct {
		Id       int64     `db:"id"`
		UserId   int64     `db:"user_id"`
		GoodsId  int64     `db:"goods_id"`
		Count    int64     `db:"count"`
		Status   int64     `db:"status"`
		CreateAt time.Time `db:"create_at"`
		UpdateAt time.Time `db:"update_at"`
	}
)

func newMallOrderModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMallOrderModel {
	return &defaultMallOrderModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`mall_order`",
	}
}

func (m *defaultMallOrderModel) Delete(ctx context.Context, id int64) error {
	mallOrderIdKey := fmt.Sprintf("%s%v", cacheMallOrderIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, mallOrderIdKey)
	return err
}

func (m *defaultMallOrderModel) FindOne(ctx context.Context, id int64) (*MallOrder, error) {
	mallOrderIdKey := fmt.Sprintf("%s%v", cacheMallOrderIdPrefix, id)
	var resp MallOrder
	err := m.QueryRowCtx(ctx, &resp, mallOrderIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mallOrderRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMallOrderModel) Insert(ctx context.Context, data *MallOrder) (sql.Result, error) {
	mallOrderIdKey := fmt.Sprintf("%s%v", cacheMallOrderIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, mallOrderRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.GoodsId, data.Count, data.Status)
	}, mallOrderIdKey)
	return ret, err
}

func (m *defaultMallOrderModel) Update(ctx context.Context, data *MallOrder) error {
	mallOrderIdKey := fmt.Sprintf("%s%v", cacheMallOrderIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mallOrderRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.GoodsId, data.Count, data.Status, data.Id)
	}, mallOrderIdKey)
	return err
}

func (m *defaultMallOrderModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMallOrderIdPrefix, primary)
}

func (m *defaultMallOrderModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mallOrderRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMallOrderModel) tableName() string {
	return m.table
}
