// Code generated by goctl. DO NOT EDIT.
// Source: parser.proto

package server

import (
	"context"

	"rsapi/converter/rpc/parser/internal/logic"
	"rsapi/converter/rpc/parser/internal/svc"
	"rsapi/converter/rpc/parser/parser"
)

type ParserServer struct {
	svcCtx *svc.ServiceContext
	parser.UnimplementedParserServer
}

func NewParserServer(svcCtx *svc.ServiceContext) *ParserServer {
	return &ParserServer{
		svcCtx: svcCtx,
	}
}

func (s *ParserServer) Ping(ctx context.Context, in *parser.Request) (*parser.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
