// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: usage.proto

package usage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Usage_Ping_FullMethodName = "/usage.Usage/Ping"
)

// UsageClient is the client API for Usage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UsageClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type usageClient struct {
	cc grpc.ClientConnInterface
}

func NewUsageClient(cc grpc.ClientConnInterface) UsageClient {
	return &usageClient{cc}
}

func (c *usageClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Usage_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsageServer is the server API for Usage service.
// All implementations must embed UnimplementedUsageServer
// for forward compatibility
type UsageServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedUsageServer()
}

// UnimplementedUsageServer must be embedded to have forward compatible implementations.
type UnimplementedUsageServer struct {
}

func (UnimplementedUsageServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedUsageServer) mustEmbedUnimplementedUsageServer() {}

// UnsafeUsageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsageServer will
// result in compilation errors.
type UnsafeUsageServer interface {
	mustEmbedUnimplementedUsageServer()
}

func RegisterUsageServer(s grpc.ServiceRegistrar, srv UsageServer) {
	s.RegisterService(&Usage_ServiceDesc, srv)
}

func _Usage_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Usage_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Usage_ServiceDesc is the grpc.ServiceDesc for Usage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Usage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usage.Usage",
	HandlerType: (*UsageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Usage_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usage.proto",
}
