// Code generated by goctl. DO NOT EDIT.
// Source: bucket.proto

package server

import (
	"context"

	"rsapi/oss/rpc/bucket/bucket"
	"rsapi/oss/rpc/bucket/internal/logic"
	"rsapi/oss/rpc/bucket/internal/svc"
)

type BucketServer struct {
	svcCtx *svc.ServiceContext
	bucket.UnimplementedBucketServer
}

func NewBucketServer(svcCtx *svc.ServiceContext) *BucketServer {
	return &BucketServer{
		svcCtx: svcCtx,
	}
}

func (s *BucketServer) Ping(ctx context.Context, in *bucket.Request) (*bucket.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
