// Code generated by goctl. DO NOT EDIT.
// Source: bucket.proto

package bucketclient

import (
	"context"

	"rsapi/oss/rpc/bucket/bucket"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = bucket.Request
	Response = bucket.Response

	Bucket interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultBucket struct {
		cli zrpc.Client
	}
)

func NewBucket(cli zrpc.Client) Bucket {
	return &defaultBucket{
		cli: cli,
	}
}

func (m *defaultBucket) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := bucket.NewBucketClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
