// Code generated by goctl. DO NOT EDIT.
// Source: formatter.proto

package formatterclient

import (
	"context"

	"rsapi/devtoys/rpc/formatter/formatter"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = formatter.Request
	Response = formatter.Response

	Formatter interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultFormatter struct {
		cli zrpc.Client
	}
)

func NewFormatter(cli zrpc.Client) Formatter {
	return &defaultFormatter{
		cli: cli,
	}
}

func (m *defaultFormatter) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := formatter.NewFormatterClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
