// Code generated by goctl. DO NOT EDIT.
// Source: item.proto

package itemclient

import (
	"context"

	"rsapi/recommend/rpc/item/item"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = item.Request
	Response = item.Response

	Item interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultItem struct {
		cli zrpc.Client
	}
)

func NewItem(cli zrpc.Client) Item {
	return &defaultItem{
		cli: cli,
	}
}

func (m *defaultItem) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := item.NewItemClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
