// Code generated by goctl. DO NOT EDIT.
// Source: goods.proto

package server

import (
	"context"

	"rsapi/mall/rpc/goods/goods"
	"rsapi/mall/rpc/goods/internal/logic"
	"rsapi/mall/rpc/goods/internal/svc"
)

type GoodsServer struct {
	svcCtx *svc.ServiceContext
	goods.UnimplementedGoodsServer
}

func NewGoodsServer(svcCtx *svc.ServiceContext) *GoodsServer {
	return &GoodsServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsServer) Add(ctx context.Context, in *goods.AddReq) (*goods.AddRes, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}

func (s *GoodsServer) Edit(ctx context.Context, in *goods.EditReq) (*goods.EditRes, error) {
	l := logic.NewEditLogic(ctx, s.svcCtx)
	return l.Edit(in)
}

func (s *GoodsServer) List(ctx context.Context, in *goods.ListReq) (*goods.ListRes, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *GoodsServer) Detail(ctx context.Context, in *goods.DetailReq) (*goods.DetailRes, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}

func (s *GoodsServer) Delete(ctx context.Context, in *goods.DeleteReq) (*goods.DeleteRes, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}
