// Code generated by goctl. DO NOT EDIT.
// Source: item.proto

package server

import (
	"context"

	"rsapi/recommend/rpc/item/internal/logic"
	"rsapi/recommend/rpc/item/internal/svc"
	"rsapi/recommend/rpc/item/item"
)

type ItemServer struct {
	svcCtx *svc.ServiceContext
	item.UnimplementedItemServer
}

func NewItemServer(svcCtx *svc.ServiceContext) *ItemServer {
	return &ItemServer{
		svcCtx: svcCtx,
	}
}

func (s *ItemServer) Ping(ctx context.Context, in *item.Request) (*item.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
