// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: requester.proto

package requester

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Requester_Ping_FullMethodName = "/requester.Requester/Ping"
)

// RequesterClient is the client API for Requester service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RequesterClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type requesterClient struct {
	cc grpc.ClientConnInterface
}

func NewRequesterClient(cc grpc.ClientConnInterface) RequesterClient {
	return &requesterClient{cc}
}

func (c *requesterClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Requester_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequesterServer is the server API for Requester service.
// All implementations must embed UnimplementedRequesterServer
// for forward compatibility
type RequesterServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedRequesterServer()
}

// UnimplementedRequesterServer must be embedded to have forward compatible implementations.
type UnimplementedRequesterServer struct {
}

func (UnimplementedRequesterServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRequesterServer) mustEmbedUnimplementedRequesterServer() {}

// UnsafeRequesterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequesterServer will
// result in compilation errors.
type UnsafeRequesterServer interface {
	mustEmbedUnimplementedRequesterServer()
}

func RegisterRequesterServer(s grpc.ServiceRegistrar, srv RequesterServer) {
	s.RegisterService(&Requester_ServiceDesc, srv)
}

func _Requester_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequesterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Requester_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequesterServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Requester_ServiceDesc is the grpc.ServiceDesc for Requester service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Requester_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "requester.Requester",
	HandlerType: (*RequesterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Requester_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "requester.proto",
}
