// Code generated by goctl. DO NOT EDIT.
// Source: adapter.proto

package adapterclient

import (
	"context"

	"rsapi/converter/rpc/adapter/adapter"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = adapter.Request
	Response = adapter.Response

	Adapter interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultAdapter struct {
		cli zrpc.Client
	}
)

func NewAdapter(cli zrpc.Client) Adapter {
	return &defaultAdapter{
		cli: cli,
	}
}

func (m *defaultAdapter) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := adapter.NewAdapterClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
