// Code generated by goctl. DO NOT EDIT.
// Source: codec.proto

package server

import (
	"context"

	"rsapi/devtoys/rpc/codec/codec"
	"rsapi/devtoys/rpc/codec/internal/logic"
	"rsapi/devtoys/rpc/codec/internal/svc"
)

type CodecServer struct {
	svcCtx *svc.ServiceContext
	codec.UnimplementedCodecServer
}

func NewCodecServer(svcCtx *svc.ServiceContext) *CodecServer {
	return &CodecServer{
		svcCtx: svcCtx,
	}
}

func (s *CodecServer) Ping(ctx context.Context, in *codec.Request) (*codec.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
