// Code generated by goctl. DO NOT EDIT.
// Source: usage.proto

package server

import (
	"context"

	"rsapi/oss/rpc/usage/internal/logic"
	"rsapi/oss/rpc/usage/internal/svc"
	"rsapi/oss/rpc/usage/usage"
)

type UsageServer struct {
	svcCtx *svc.ServiceContext
	usage.UnimplementedUsageServer
}

func NewUsageServer(svcCtx *svc.ServiceContext) *UsageServer {
	return &UsageServer{
		svcCtx: svcCtx,
	}
}

func (s *UsageServer) Ping(ctx context.Context, in *usage.Request) (*usage.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
