// Code generated by goctl. DO NOT EDIT.
// Source: room.proto

package server

import (
	"context"

	"rsapi/chat/rpc/room/internal/logic"
	"rsapi/chat/rpc/room/internal/svc"
	"rsapi/chat/rpc/room/room"
)

type RoomServer struct {
	svcCtx *svc.ServiceContext
	room.UnimplementedRoomServer
}

func NewRoomServer(svcCtx *svc.ServiceContext) *RoomServer {
	return &RoomServer{
		svcCtx: svcCtx,
	}
}

func (s *RoomServer) Ping(ctx context.Context, in *room.Request) (*room.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
