// Code generated by goctl. DO NOT EDIT.
// Source: cart.proto

package server

import (
	"context"

	"rsapi/mall/rpc/cart/cart"
	"rsapi/mall/rpc/cart/internal/logic"
	"rsapi/mall/rpc/cart/internal/svc"
)

type CartServer struct {
	svcCtx *svc.ServiceContext
	cart.UnimplementedCartServer
}

func NewCartServer(svcCtx *svc.ServiceContext) *CartServer {
	return &CartServer{
		svcCtx: svcCtx,
	}
}

func (s *CartServer) Push(ctx context.Context, in *cart.PushReq) (*cart.PushRes, error) {
	l := logic.NewPushLogic(ctx, s.svcCtx)
	return l.Push(in)
}

func (s *CartServer) Pop(ctx context.Context, in *cart.PopReq) (*cart.PopRes, error) {
	l := logic.NewPopLogic(ctx, s.svcCtx)
	return l.Pop(in)
}

func (s *CartServer) List(ctx context.Context, in *cart.ListReq) (*cart.ListRes, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}
