// Code generated by goctl. DO NOT EDIT.
// Source: builder.proto

package builderclient

import (
	"context"

	"rsapi/converter/rpc/builder/builder"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = builder.Request
	Response = builder.Response

	Builder interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultBuilder struct {
		cli zrpc.Client
	}
)

func NewBuilder(cli zrpc.Client) Builder {
	return &defaultBuilder{
		cli: cli,
	}
}

func (m *defaultBuilder) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := builder.NewBuilderClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
