// Code generated by goctl. DO NOT EDIT.
// Source: token.proto

package server

import (
	"context"

	"rsapi/auth/rpc/token/internal/logic"
	"rsapi/auth/rpc/token/internal/svc"
	"rsapi/auth/rpc/token/token"
)

type TokenServer struct {
	svcCtx *svc.ServiceContext
	token.UnimplementedTokenServer
}

func NewTokenServer(svcCtx *svc.ServiceContext) *TokenServer {
	return &TokenServer{
		svcCtx: svcCtx,
	}
}

func (s *TokenServer) Generate(ctx context.Context, in *token.GenerateReq) (*token.GenerateRes, error) {
	l := logic.NewGenerateLogic(ctx, s.svcCtx)
	return l.Generate(in)
}

func (s *TokenServer) Verify(ctx context.Context, in *token.VerifyReq) (*token.VerifyRes, error) {
	l := logic.NewVerifyLogic(ctx, s.svcCtx)
	return l.Verify(in)
}

func (s *TokenServer) Invalid(ctx context.Context, in *token.InvalidReq) (*token.InvalidRes, error) {
	l := logic.NewInvalidLogic(ctx, s.svcCtx)
	return l.Invalid(in)
}
