// Code generated by goctl. DO NOT EDIT.
// Source: storer.proto

package storerclient

import (
	"context"

	"rsapi/grab/rpc/storer/storer"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = storer.Request
	Response = storer.Response

	Storer interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultStorer struct {
		cli zrpc.Client
	}
)

func NewStorer(cli zrpc.Client) Storer {
	return &defaultStorer{
		cli: cli,
	}
}

func (m *defaultStorer) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := storer.NewStorerClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
