// Code generated by goctl. DO NOT EDIT.
// Source: requester.proto

package requesterclient

import (
	"context"

	"rsapi/grab/rpc/requester/requester"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = requester.Request
	Response = requester.Response

	Requester interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultRequester struct {
		cli zrpc.Client
	}
)

func NewRequester(cli zrpc.Client) Requester {
	return &defaultRequester{
		cli: cli,
	}
}

func (m *defaultRequester) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := requester.NewRequesterClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
