// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: ptop.proto

package ptop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Ptop_Ping_FullMethodName = "/ptop.Ptop/Ping"
)

// PtopClient is the client API for Ptop service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PtopClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type ptopClient struct {
	cc grpc.ClientConnInterface
}

func NewPtopClient(cc grpc.ClientConnInterface) PtopClient {
	return &ptopClient{cc}
}

func (c *ptopClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Ptop_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PtopServer is the server API for Ptop service.
// All implementations must embed UnimplementedPtopServer
// for forward compatibility
type PtopServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedPtopServer()
}

// UnimplementedPtopServer must be embedded to have forward compatible implementations.
type UnimplementedPtopServer struct {
}

func (UnimplementedPtopServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPtopServer) mustEmbedUnimplementedPtopServer() {}

// UnsafePtopServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PtopServer will
// result in compilation errors.
type UnsafePtopServer interface {
	mustEmbedUnimplementedPtopServer()
}

func RegisterPtopServer(s grpc.ServiceRegistrar, srv PtopServer) {
	s.RegisterService(&Ptop_ServiceDesc, srv)
}

func _Ptop_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PtopServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ptop_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PtopServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Ptop_ServiceDesc is the grpc.ServiceDesc for Ptop service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ptop_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ptop.Ptop",
	HandlerType: (*PtopServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Ptop_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ptop.proto",
}
