// Code generated by goctl. DO NOT EDIT.
// Source: p2p.proto

package server

import (
	"context"

	"rsapi/chat/rpc/p2p/internal/logic"
	"rsapi/chat/rpc/p2p/internal/svc"
	"rsapi/chat/rpc/p2p/p2p"
)

type P2pServer struct {
	svcCtx *svc.ServiceContext
	p2p.UnimplementedP2pServer
}

func NewP2pServer(svcCtx *svc.ServiceContext) *P2pServer {
	return &P2pServer{
		svcCtx: svcCtx,
	}
}

func (s *P2pServer) Ping(ctx context.Context, in *p2p.Request) (*p2p.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
