// Code generated by goctl. DO NOT EDIT.
// Source: rank.proto

package server

import (
	"context"

	"rsapi/recommend/rpc/rank/internal/logic"
	"rsapi/recommend/rpc/rank/internal/svc"
	"rsapi/recommend/rpc/rank/rank"
)

type RankServer struct {
	svcCtx *svc.ServiceContext
	rank.UnimplementedRankServer
}

func NewRankServer(svcCtx *svc.ServiceContext) *RankServer {
	return &RankServer{
		svcCtx: svcCtx,
	}
}

func (s *RankServer) Ping(ctx context.Context, in *rank.Request) (*rank.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
