// Code generated by goctl. DO NOT EDIT.
// Source: builder.proto

package server

import (
	"context"

	"rsapi/converter/rpc/builder/builder"
	"rsapi/converter/rpc/builder/internal/logic"
	"rsapi/converter/rpc/builder/internal/svc"
)

type BuilderServer struct {
	svcCtx *svc.ServiceContext
	builder.UnimplementedBuilderServer
}

func NewBuilderServer(svcCtx *svc.ServiceContext) *BuilderServer {
	return &BuilderServer{
		svcCtx: svcCtx,
	}
}

func (s *BuilderServer) Ping(ctx context.Context, in *builder.Request) (*builder.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
