// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: formatter.proto

package formatter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Formatter_Ping_FullMethodName = "/formatter.Formatter/Ping"
)

// FormatterClient is the client API for Formatter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FormatterClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type formatterClient struct {
	cc grpc.ClientConnInterface
}

func NewFormatterClient(cc grpc.ClientConnInterface) FormatterClient {
	return &formatterClient{cc}
}

func (c *formatterClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Formatter_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FormatterServer is the server API for Formatter service.
// All implementations must embed UnimplementedFormatterServer
// for forward compatibility
type FormatterServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedFormatterServer()
}

// UnimplementedFormatterServer must be embedded to have forward compatible implementations.
type UnimplementedFormatterServer struct {
}

func (UnimplementedFormatterServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedFormatterServer) mustEmbedUnimplementedFormatterServer() {}

// UnsafeFormatterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FormatterServer will
// result in compilation errors.
type UnsafeFormatterServer interface {
	mustEmbedUnimplementedFormatterServer()
}

func RegisterFormatterServer(s grpc.ServiceRegistrar, srv FormatterServer) {
	s.RegisterService(&Formatter_ServiceDesc, srv)
}

func _Formatter_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FormatterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Formatter_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FormatterServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Formatter_ServiceDesc is the grpc.ServiceDesc for Formatter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Formatter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "formatter.Formatter",
	HandlerType: (*FormatterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Formatter_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "formatter.proto",
}
