// Code generated by goctl. DO NOT EDIT.
// Source: strategy.proto

package strategyclient

import (
	"context"

	"rsapi/recommend/rpc/strategy/strategy"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = strategy.Request
	Response = strategy.Response

	Strategy interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultStrategy struct {
		cli zrpc.Client
	}
)

func NewStrategy(cli zrpc.Client) Strategy {
	return &defaultStrategy{
		cli: cli,
	}
}

func (m *defaultStrategy) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := strategy.NewStrategyClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
