// Code generated by goctl. DO NOT EDIT.
// Source: storer.proto

package server

import (
	"context"

	"rsapi/grab/rpc/storer/internal/logic"
	"rsapi/grab/rpc/storer/internal/svc"
	"rsapi/grab/rpc/storer/storer"
)

type StorerServer struct {
	svcCtx *svc.ServiceContext
	storer.UnimplementedStorerServer
}

func NewStorerServer(svcCtx *svc.ServiceContext) *StorerServer {
	return &StorerServer{
		svcCtx: svcCtx,
	}
}

func (s *StorerServer) Ping(ctx context.Context, in *storer.Request) (*storer.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
