// Code generated by goctl. DO NOT EDIT.
// Source: ptop.proto

package ptopclient

import (
	"context"

	"rsapi/chat/rpc/ptop/ptop"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = ptop.Request
	Response = ptop.Response

	Ptop interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultPtop struct {
		cli zrpc.Client
	}
)

func NewPtop(cli zrpc.Client) Ptop {
	return &defaultPtop{
		cli: cli,
	}
}

func (m *defaultPtop) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := ptop.NewPtopClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
