// Code generated by goctl. DO NOT EDIT.
// Source: generator.proto

package server

import (
	"context"

	"rsapi/devtoys/rpc/generator/generator"
	"rsapi/devtoys/rpc/generator/internal/logic"
	"rsapi/devtoys/rpc/generator/internal/svc"
)

type GeneratorServer struct {
	svcCtx *svc.ServiceContext
	generator.UnimplementedGeneratorServer
}

func NewGeneratorServer(svcCtx *svc.ServiceContext) *GeneratorServer {
	return &GeneratorServer{
		svcCtx: svcCtx,
	}
}

func (s *GeneratorServer) Ping(ctx context.Context, in *generator.Request) (*generator.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
